### ISSUE TITLE
Create common Github Actions workflow for testing IaC

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-common-workflows#25]
As a UDS dev
I want a common CI workflow for testing IaC
So that I can easily run standardized tests in IaC repos

**Comment by wirewc** [comment]
Command that should be used for the pipeline: `go test -count 1 -v ./...`. Commenting for making a note from a test repository.

**Comment by wirewc** [comment]
@UncleGedd with regards to secrets that are needed for testing in a common workflow, I am curious how to proceed. The options for handle credentials that I see are of the following:
* Secrets for the infrastructure should be identified at the IaC repository level and set before the testing workflow is called and just assumed to be retained as an environment variable prior to the workflow executing. 
* Secrets should be identified and passed to the shared workflow as an argument. 
* Secrets should be managed by the shared workflow only. 

What is the best way we want to proceed with handling infrastructure secrets?

**Comment by UncleGedd** [comment]
IMO we should lean towards putting the secrets in the individual repo and use that [secrets.inherit](https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/) pattern. I don't think we want to use the same secret across all repos, and it feels strange to me to put secrets in common workflows that are public

**Comment by wirewc** [comment]
Thank you for the feedback @UncleGedd. I was leaning a different way but I can work with this. Thank you!
