### ISSUE TITLE
Terratest not outputting status until the end

### ISSUE THREAD

**Issue by wirewc** [defenseunicorns/uds-common-workflows#48]
**Problem Statement:** When running Terratest, any logging, outputs, or status are not published until Terratest is completed. This behavior means longer feedback cycles impacting velocity. Additionally, longer pipelines may cause issues with Terratest as the pipelines may give false signals the pipeline is stuck and idling until timeout. 

```[tasklist]
### Acceptance Criteria:
- [x] Post relevant research
- [x] Propose an immediate solution
- [ ] Post a comment if the immediate solution has room for improvement (with suggestions if possible)
```

**Comment by wirewc** [comment]
Relevant research: https://github.com/golang/go/issues/46959

Root cause, parallel testing will only produce log messages at the end of the test run.

**Comment by wirewc** [comment]
Previous work helped prove the research from the previous comment. Work has been captured in [this branch](https://github.com/defenseunicorns/terraform-aws-uds-s3/tree/example-test-refactor). 

*Original assumption:* The way the test was written was causing a difference in how the output was working. 

*Conclusion:* How someone uses Terratest does not impact how the logging is shown during run time at all. The solution that works the best is to test with `go test ./... -count 1 -p 1 -v`. 

**Action:** Changing the `go test` command to remove parallel testing for now.

**Comment by wirewc** [comment]
**Potential Consequences:** Removing parallelism will slow down testing. 

**Potential Future Solutions:**
* Bash scripting to execute sequenced tests 1 at a time.
* Working with matrix builds based on the number of tests needing to run. 
* Allow actions to spawn 1 test per action call.

These ideas should be discussed with the team, in addition to other approaches not listed.

**Comment by RothAndrew** [comment]
You should be able to keep parallelism if you move all test files to the same folder with the same namespace

**Comment by wirewc** [comment]
We cannot have both parallelism and the synchronous logging behavior. Both golang issue listed and personal testing confirmed this problem.

**Comment by wirewc** [comment]
Because of this issue, I would not recommend lengthy terraform testing using this common workflow until a suitable solution has been found and tested. Suggestions are always welcomed.

**Comment by RothAndrew** [comment]
> We cannot have both parallelism and the synchronous logging behavior. Both golang issue listed and personal testing confirmed this problem.

Yes you can. Let's look at it together on Monday.

**Comment by wirewc** [comment]
Thanks @RothAndrew, you are seeing something I was unable to replicate myself. I appreciate the assistance.
